In [1]:
import os
os.chdir('/Users/layne/Desktop/aiqc')

In [2]:
import aiqc
from aiqc import datum

In [3]:
from aiqc import tests

In [4]:
aiqc.destroy_db(confirm=True, rebuild=True)


=> Success - deleted database file at path:
/Users/layne/Library/Application Support/aiqc/aiqc.sqlite3


=> Success - created database file at path:
/Users/layne/Library/Application Support/aiqc/aiqc.sqlite3


💾  Success - created all database tables.  💾



---

In [5]:
b1 = tests.make_test_batch('binary')
b1.run_jobs()


___/ featurecoder_index: 0 \_________



🔮 Training Models 🔮:   0%|                                                  | 0/4 [00:00<?, ?it/s]

=> The column(s) below matched your filter(s) and were ran through a test-encoding successfully.
['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'aa',
 'ab',
 'ac',
 'ad',
 'ae',
 'af',
 'ag',
 'ah',
 'ai',
 'aj',
 'ak',
 'al',
 'am',
 'an',
 'ao',
 'ap',
 'aq',
 'ar',
 'as',
 'at',
 'au',
 'av',
 'aw',
 'ax',
 'ay',
 'az',
 'ba',
 'bb',
 'bc',
 'bd',
 'be',
 'bf',
 'bg',
 'bh']

=> Nice! Now all feature column(s) have encoder(s) associated with them.
No more Featurecoders can be added to this Encoderset.


Warning - `function_model_optimize` is not defined, so 
the optimizer must be defined within either `function_model_train` 
or `function_model_build`; otherwise training will fail.



🔮 Training Models 🔮: 100%|██████████████████████████████████████████| 4/4 [00:38<00:00,  9.56s/it]


In [6]:
b2 = tests.make_test_batch('multiclass')
b2.run_jobs()

🔮 Training Models 🔮:   0%|                                                  | 0/8 [00:00<?, ?it/s]


___/ featurecoder_index: 0 \_________

=> The column(s) below matched your filter(s) and were ran through a test-encoding successfully.
['petal_width']

=> The remaining column(s) and dtype(s) can be used in downstream Featurecoder(s):
{'petal_length': 'float64', 'sepal_length': 'float64', 'sepal_width': 'float64'}


___/ featurecoder_index: 1 \_________

=> The column(s) below matched your filter(s) and were ran through a test-encoding successfully.
['sepal_length', 'sepal_width', 'petal_length']

=> Nice! Now all feature column(s) have encoder(s) associated with them.
No more Featurecoders can be added to this Encoderset.


Warning - `function_model_optimize` is not defined, so 
the optimizer must be defined within either `function_model_train` 
or `function_model_build`; otherwise training will fail.



🔮 Training Models 🔮: 100%|██████████████████████████████████████████| 8/8 [00:29<00:00,  3.70s/it]


In [7]:
b3 = tests.make_test_batch('regression')
b3.run_jobs()

🔮 Training Models 🔮:   0%|                                                  | 0/4 [00:00<?, ?it/s]


___/ featurecoder_index: 0 \_________

=> The column(s) below matched your filter(s) and were ran through a test-encoding successfully.
['crim', 'zn', 'indus', 'nox', 'rm', 'age', 'dis', 'ptratio', 'lstat']

=> The remaining column(s) and dtype(s) can be used in downstream Featurecoder(s):
{'chas': 'int64', 'rad': 'int64', 'tax': 'int64'}


___/ featurecoder_index: 1 \_________

=> The column(s) below matched your filter(s) and were ran through a test-encoding successfully.
['chas', 'tax', 'rad']

=> Nice! Now all feature column(s) have encoder(s) associated with them.
No more Featurecoders can be added to this Encoderset.



🔮 Training Models 🔮: 100%|██████████████████████████████████████████| 4/4 [00:31<00:00,  7.90s/it]


In [8]:
batch = tests.make_test_batch('image_binary', repeat_count=4)

🖼️ Ingesting Images 🖼️: 100%|████████████████████████| 80/80 [00:05<00:00, 15.33it/s]



Warning - `function_model_optimize` is not defined, so 
the optimizer must be defined within either `function_model_train` 
or `function_model_build`; otherwise training will fail.



In [ ]:
batch.run_jobs()

🔮 Training Models 🔮:  12%|█████▏                                   | 2/16 [00:58<06:46, 29.01s/it]

---

In [5]:
from sklearn.preprocessing import LabelBinarizer, PowerTransformer, StandardScaler

In [6]:
file_path = datum.get_path('sonar.csv')

dataset = aiqc.Dataset.Tabular.from_path(
    file_path = file_path
    , source_file_format = 'csv'
    , name = 'rocks n radio'
    , dtype = None
)

label_column = 'object'
label = dataset.make_label(columns=[label_column])

featureset = dataset.make_featureset(exclude_columns=[label_column])

splitset = featureset.make_splitset(
    label_id = label.id
    , size_test = 0.27
)

encoderset = splitset.make_encoderset()

labelcoder = encoderset.make_labelcoder(
    sklearn_preprocess = LabelBinarizer(sparse_output=False)
)

fc0 = encoderset.make_featurecoder(
    sklearn_preprocess = PowerTransformer(method='yeo-johnson', copy=False)
    , dtypes = ['float64']
)


___/ featurecoder_index: 0 \_________

=> The column(s) below matched your filter(s) and were ran through a test-encoding successfully.
['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'aa',
 'ab',
 'ac',
 'ad',
 'ae',
 'af',
 'ag',
 'ah',
 'ai',
 'aj',
 'ak',
 'al',
 'am',
 'an',
 'ao',
 'ap',
 'aq',
 'ar',
 'as',
 'at',
 'au',
 'av',
 'aw',
 'ax',
 'ay',
 'az',
 'ba',
 'bb',
 'bc',
 'bd',
 'be',
 'bf',
 'bg',
 'bh']

=> Nice! Now all feature column(s) have encoder(s) associated with them.
No more Featurecoders can be added to this Encoderset.



---

In [25]:
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
from torch.nn import Sequential
from torch import optim

In [26]:
encoder_feat = StandardScaler('yeo-johnson', copy=False)
encoder_lab = LabelBinarizer(sparse_output=False)

/Users/layne/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass copy=yeo-johnson as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [27]:
data_train_feat = splitset.to_numpy()['train']['features']
data_train_lab = splitset.to_numpy()['train']['labels']

data_test_feat = splitset.to_numpy()['test']['features']
data_test_lab = splitset.to_numpy()['test']['labels']

In [28]:
data_train_feat = encoder_feat.fit_transform(data_train_feat)
data_train_lab = encoder_lab.fit_transform(data_train_lab)

data_test_feat = encoder_feat.fit_transform(data_test_feat)
data_test_lab = encoder_lab.fit_transform(data_test_lab)

In [29]:
tz_train_feat = torch.FloatTensor(data_train_feat)
tz_train_lab = torch.FloatTensor(data_train_lab)

tz_test_feat = torch.FloatTensor(data_test_feat)
tz_test_lab = torch.FloatTensor(data_test_lab)

In [30]:
tz_train_feat.shape

torch.Size([151, 60])

will this work in the functional API?

In [92]:
model = Sequential(
    nn.Linear(60, 24),
    nn.BatchNorm1d(24,24),
    nn.ReLU(),
    nn.Dropout(p=0.4),

    nn.Linear(24, 1),
    nn.Sigmoid(),
)

forward is only defined in the functional API?

In [93]:
optimizer = optim.Adamax(
    model.parameters(),
    lr=0.01
)

In [94]:
# seems like it needs to be instantiated first
loss_fn = nn.BCELoss()

now we call them.

In [95]:
%%capture
preds = model(tz_train_feat)

In [96]:
loss = loss_fn(preds, tz_train_lab)
# outputs a single scalar (aka 0-dim tensor, torch.Size([]) ) for the whole epoch?
# tensor(0.6945, grad_fn=<BinaryCrossEntropyBackward>)

In [97]:
optimizer.zero_grad()
# how does this relate to `with torch.no_grad()`

In [98]:
loss.backward()

In [98]:
optimizer.step()

^ what does this do? not related to breaking for loop?

i don't think there is a `compile`, the model and opt are just called separately 

looks like i'll have to define the loss_fn separately from the model and then call it in the loop

In [62]:
epochs = 100

it seems like batch_size is handled by the dataloader. because the dataloader is iterated over in most `forward` functions

"TypeError: linear(): argument 'input' (position 1) must be Tensor, not numpy.ndarray"

look into `DataLoader`

---

### save model

state dict
https://pytorch.org/tutorials/beginner/saving_loading_models.html

In [99]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[-0.0967,  0.0656,  0.0295,  ...,  0.0214, -0.0767, -0.0084],
                      [ 0.0903,  0.0663,  0.0691,  ..., -0.0805,  0.0507,  0.0972],
                      [-0.0472, -0.0838,  0.0054,  ...,  0.0148, -0.0732, -0.0926],
                      ...,
                      [-0.0904, -0.0823, -0.0513,  ...,  0.0063,  0.0431,  0.0384],
                      [ 0.0733,  0.0369, -0.0539,  ...,  0.0011, -0.0474, -0.0705],
                      [ 0.0365,  0.0562, -0.0443,  ..., -0.1169,  0.0324,  0.0425]])),
             ('0.bias',
              tensor([ 0.1104, -0.0514,  0.0278,  0.0341, -0.0081, -0.0594, -0.0086,  0.1202,
                       0.0902, -0.0891,  0.0299,  0.0080,  0.0718, -0.0367, -0.0250, -0.0038,
                      -0.0722, -0.0783,  0.0195,  0.1138, -0.0545, -0.0376, -0.0097,  0.0385])),
             ('1.weight',
              tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           

In [100]:
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.01,
   'betas': (0.9, 0.999),
   'eps': 1e-08,
   'weight_decay': 0,
   'params': [0, 1, 2, 3, 4, 5]}]}

In [101]:
import pickle, io

In [108]:
model_blob = io.BytesIO()

how to save optimizer?

In [109]:
torch.save({
    'model_state_dict': model.state_dict()
    },
    model_blob
)

In [110]:
model_blob = model_blob.getvalue()

In [111]:
model_blob = io.BytesIO(model_blob)

In [112]:
checkpoint = torch.load(model_blob)

In [114]:
new_model = model.load_state_dict(
    checkpoint['model_state_dict']
)

In [69]:
from datetime import datetime

how to get history?... skip it for pytorch for now?

In [72]:
model.__class__

torch.nn.modules.container.Sequential

In [73]:
model

Sequential(
  (0): Linear(in_features=60, out_features=24, bias=True)
  (1): BatchNorm1d(24, eps=24, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU()
  (3): Dropout(p=0.4, inplace=False)
  (4): Linear(in_features=24, out_features=1, bias=True)
  (5): Sigmoid()
)

In [74]:
model.__init__()

In [75]:
model

Sequential()

In [75]:
{
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict()
}

Sequential()

`load_state_dict`