In [1]:
import numpy as np

In [2]:
arr = [
    [1.1, 2.2, 3.3],
    [1.1, 2.2, 3.3],
    [1.1, 2.2, 3.3],
]

In [3]:
arr = np.array(arr)

In [4]:
arr

array([[1.1, 2.2, 3.3],
       [1.1, 2.2, 3.3],
       [1.1, 2.2, 3.3]])

In [5]:
arr / 1

array([[1.1, 2.2, 3.3],
       [1.1, 2.2, 3.3],
       [1.1, 2.2, 3.3]])

In [6]:
arr / 0.5

array([[2.2, 4.4, 6.6],
       [2.2, 4.4, 6.6],
       [2.2, 4.4, 6.6]])

In [7]:
arr3D = [
    [
        [1.1, 1.1, 1.1],
        [1.1, 1.1, 1.1],
        [1.1, 1.1, 1.1],
    ],
    [
        [2.2, 2.2, 2.2],
        [2.2, 2.2, 2.2],
        [2.2, 2.2, 2.2],
    ],
    [
        [3.3, 3.3, 3.3],
        [3.3, 3.3, 3.3],
        [3.3, 3.3, 3.3],
    ],
]

In [8]:
arr3D = np.array(arr3D)

In [10]:
arr3D / 1.37

array([[[0.80291971, 0.80291971, 0.80291971],
        [0.80291971, 0.80291971, 0.80291971],
        [0.80291971, 0.80291971, 0.80291971]],

       [[1.60583942, 1.60583942, 1.60583942],
        [1.60583942, 1.60583942, 1.60583942],
        [1.60583942, 1.60583942, 1.60583942]],

       [[2.40875912, 2.40875912, 2.40875912],
        [2.40875912, 2.40875912, 2.40875912],
        [2.40875912, 2.40875912, 2.40875912]]])