In [16]:
import os
os.chdir("/Users/Layne/Downloads")

In [5]:
pip uninstall gitdir -y

Found existing installation: gitdir 1.2.4
Uninstalling gitdir-1.2.4:
  Successfully uninstalled gitdir-1.2.4
Note: you may need to restart the kernel to use updated packages.


In [13]:
os.system("curl https://raw.githubusercontent.com/aiqc/aiqc/main/aiqc/data/iris.tsv > iris.tsv")

0

In [17]:
os.mkdir("images_brain")

FileExistsError: [Errno 17] File exists: 'brain_tumor_images'

In [18]:
os.chdir("images_brain")

Windows10 includes curl by default
https://superuser.com/a/755581/542414

In [19]:
os.system("curl https://raw.githubusercontent.com/aiqc/aiqc/main/aiqc/data/iris.tsv > iris.tsv")

0

In [18]:
pip install gitpython

You should consider upgrading via the '/Users/layne/.pyenv/versions/3.7.6/envs/jupyterlab/bin/python3.7 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [20]:
import os
from git.repo.base import Repo

In [26]:
Repo.clone_from("https://github.com/aiqc/aiqc", "/tree/main/images", branch='main')

GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --branch=main -v https://github.com/aiqc/aiqc /images
  stderr: 'fatal: could not create work tree dir '/images': Read-only file system
'

In [88]:
import numpy as np
import pandas as pd

In [89]:
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder

In [90]:
records = [
    {'name': 'bob', 'size': 0.54, 'height': 3.1, 'mode': 1},
    {'name': 'jim', 'size': 0.23, 'height': 6.2, 'mode': 2},
    {'name': 'larry', 'size': 0.77, 'height': 132.5, 'mode': 3}
]

In [91]:
df = pd.DataFrame.from_records(records)

In [92]:
df.dtypes

name       object
size      float64
height    float64
mode        int64
dtype: object

In [93]:
df.select_dtypes('object')

name
0    bob
1    jim
2  larry

In [94]:
scaler = StandardScaler()

In [95]:
scaler.fit(df[['size','height']])

StandardScaler()

In [96]:
scaler.fit_transform(
    df[['size','height']]
)

array([[ 0.12052239, -0.73266327],
       [-1.28055041, -0.6812386 ],
       [ 1.16002802,  1.41390187]])

In [97]:
ordiner = OrdinalEncoder()

In [98]:
ordiner.fit_transform(
    df[['mode']]
)

array([[0.],
       [1.],
       [2.]])

In [99]:
ordiner.fit_transform(
    df.select_dtypes(include='object')
)

array([[0.],
       [1.],
       [2.]])

In [100]:
df.select_dtypes(exclude='object').columns.to_list()

['size', 'height', 'mode']

In [101]:
class Preprocess:
    featureset_encoders:list
    label_encoder:list

In [102]:
preproc = Preprocess()
preproc.featureset_encoder = [
    {
        "selector":"dtypes"
        , "include":['int']
        , "encoder": OrdinalEncoder()
    },
    {
        "selector":"dtypes"
        , "include":['float'] 
        , "encoder": StandardScaler()
    }
    #add column_name filters
]

preproc.label_encoder = OneHotEncoder(sparse=False)

In [103]:
preproc.featureset_encoder

[{'selector': 'dtypes', 'include': ['int'], 'encoder': OrdinalEncoder()},
 {'selector': 'dtypes', 'include': ['float'], 'encoder': StandardScaler()}]

---

In [104]:
subset_details = preproc.featureset_encoder[0]

In [105]:
subset_encoder = subset_details['encoder']

In [106]:
subset = df.select_dtypes(subset_details['include'])

In [107]:
subset_cols = subset.columns.to_list()

In [108]:
subset_encoded_arr = subset_encoder.fit_transform(subset)

In [109]:
subset_details_2 = preproc.featureset_encoder[1]

In [110]:
subset_encoder_2 = subset_details_2['encoder']

In [111]:
subset_2 = df.select_dtypes(subset_details_2['include'])

In [112]:
subset_cols_2 = subset_2.columns.to_list()

In [113]:
subset_encoded_arr_2 = subset_encoder_2.fit_transform(subset_2)

In [114]:
subset_encoded_arr_2

array([[ 0.12052239, -0.73266327],
       [-1.28055041, -0.6812386 ],
       [ 1.16002802,  1.41390187]])

In [115]:
subset_encoded_arr

array([[0.],
       [1.],
       [2.]])

In [116]:
subset_encoded_arr_2

array([[ 0.12052239, -0.73266327],
       [-1.28055041, -0.6812386 ],
       [ 1.16002802,  1.41390187]])

In [117]:
np.concatenate((subset_encoded_arr, subset_encoded_arr_2), axis=-1)

array([[ 0.        ,  0.12052239, -0.73266327],
       [ 1.        , -1.28055041, -0.6812386 ],
       [ 2.        ,  1.16002802,  1.41390187]])

In [118]:
encoded_cols = []

In [119]:
for c in subset_cols:
    encoded_cols.append(c)

In [120]:
for c in subset_cols_2:
    encoded_cols.append(c)

In [121]:
encoded_cols

['mode', 'size', 'height']

In [125]:
# should do this as often as possible to reduce memory?
df = df[df.columns.difference(encoded_cols, sort=False)]

In [126]:
#df = df.drop(encoded_cols, axis=1)

In [127]:
df

name
0    bob
1    jim
2  larry

In [127]:
df

name
0    bob
1    jim
2  larry