In [1]:
from numpy import array
data = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

LSTMs want 3D data even for a single sample.

In [2]:
data = data.reshape((1, 10, 1))

In [3]:
data

array([[[0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9],
        [1. ]]])

In [4]:
data[0]

array([[0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [5]:
data[0][0]

array([0.1])

In [8]:
import numpy as np
from glob import glob

In [10]:
!pwd

/Users/layne/Desktop/aiqc/notebooks


In [9]:
import os

In [14]:
os.chdir('/Users/layne/Desktop/aiqc/notebooks')

In [162]:
def get_seqs(seqs_dir:str):
    # hmmm. windows path...
    target_dir = seqs_dir + "/*"
    file_names = glob(target_dir)
    
    # make each file into a 2D array.
    two_ds = [np.loadtxt(f) for f in file_names]
    
    # if the file only had 1 feature then it still needs work to be made 2D
    try: two_ds[0].shape[1]
    except: two_ds = [np.reshape(a, (a.size, 1)) for a in two_ds]
    
    three_d = np.array(two_ds)
    return three_d

In [165]:
seqs_dir = '/Users/layne/Desktop/aiqc/notebooks/sequences_multi_feat'

In [166]:
get_seqs(seqs_dir)

array([[[13., 14.],
        [15., 16.],
        [17., 18.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]]])