In [1]:
import os
os.chdir('/Users/layne/Desktop/aiqc')
os.getcwd()

'/Users/layne/Desktop/aiqc'

In [2]:
import aiqc
from aiqc import examples

/Users/layne/.pyenv/versions/3.7.6/envs/jupyterlab/lib/python3.7/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import *

In [3]:
# from importlib import reload
# aiqc.delete_db(True)
# reload(aiqc)
# aiqc.create_db()


=> Success - deleted database file at path:
/Users/layne/Library/Application Support/aiqc/aiqc.sqlite3


=> Success - created database file for machine learning metrics at path:
/Users/layne/Library/Application Support/aiqc/aiqc.sqlite3


=> Success - created the following tables within database:
['algorithm', 'batch', 'dataset', 'encoderset', 'featureset', 'file', 'fold', 'foldset', 'hyperparamcombo', 'hyperparamset', 'image', 'job', 'jobset', 'label', 'labelcoder', 'result', 'splitset', 'tabular']



---

Str Category

In [100]:
kingdom_lst = [
    'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 'kokiri', 
    'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 'hylian', 
    'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 'gerudo', 
]

Int OHE

In [101]:
shape_lst = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
]

In [102]:
color_lst = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
]

Int Pre-Ordinal

In [103]:
month_lst = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
]

In [104]:
moon_day_lst = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
    1, 2, 3, 4
]

Str Pre-Ordinal

In [105]:
hour_lst = [
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', 'twenty-one', 'twenty-two', 'twenty-three', 'twenty-four',
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', 'twenty-one', 'twenty-two', 'twenty-three', 'twenty-four',
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', 'twenty-one', 'twenty-two', 'twenty-three', 'twenty-four',
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', 'twenty-one', 'twenty-two', 'twenty-three', 'twenty-four',
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', 'twenty-one', 'twenty-two', 'twenty-three', 'twenty-four',
]

In [106]:
weekday_lst = [
    'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday','sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday','sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday','sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'
]

Floats

In [107]:
temp_lst = [1.5*n for i,n in enumerate(range(120))]

In [108]:
radiance_lst = [(-1)*2.0*0.05*(n+1) for i,n in enumerate(range(120))]

In [109]:
doom_factor_lst = [(100000.5 - 69.13*3*n) for i,n in enumerate(range(120))]

---

In [110]:
list_of_lists = [doom_factor_lst, radiance_lst, temp_lst, weekday_lst, hour_lst, moon_day_lst, month_lst, color_lst, shape_lst, kingdom_lst]

In [111]:
for l in list_of_lists:
    if len(l) != 120:
        print(f"{l}: length {len(l)}")

In [112]:
arrays = [np.array(l) for l in list_of_lists]

In [113]:
arrays_tup = tuple(arrays)

In [114]:
array_of_arrays = np.column_stack(arrays_tup)

In [115]:
column_names = ['doom_float64', 'radiance_float32', 'temperature_float', 'weekday_object', 'hour_object', 'moonday_int64', 'month_int32', 'color_uint8', 'shape_int', 'kingdom_category']

In [116]:
df = pd.DataFrame(array_of_arrays)

In [117]:
column_dict = {}
for i, n in enumerate(column_names):
    column_dict[i] = n

In [118]:
df = df.rename(columns=column_dict)

In [10]:
df = df.astype(dtype=dtype)

In [11]:
df.dtypes

doom_float64          float64
radiance_float32      float32
temperature_float     float64
weekday_object         object
hour_object            string
moonday_int64           int64
month_int32             int32
color_uint8             uint8
shape_int               int64
kingdom_category     category
dtype: object

In [12]:
df.to_parquet("/Users/Layne/Desktop/aiqc/aiqc/data/dtype_testing.parquet", index=None)

In [5]:
df = pd.read_parquet("/Users/Layne/Desktop/aiqc/aiqc/data/dtype_testing.parquet")

In [6]:
df.dtypes

doom_float64          float64
radiance_float32      float32
temperature_float     float64
weekday_object         object
hour_object            string
moonday_int64           int64
month_int32             int32
color_uint8             uint8
shape_int               int64
kingdom_category     category
dtype: object

In [8]:
dtype = {
    'doom_float64': 'float64'
    , 'radiance_float32': 'float32'
    , 'temperature_float': 'float'
    , 'moonday_int64': 'int64'
    , 'month_int32': 'int32'
    , 'color_uint8': 'uint8'
    , 'shape_int': 'int'
    , 'weekday_object': 'object'
    , 'hour_object': 'string'
    , 'kingdom_category': 'category'
}

---

In [9]:
dataset = aiqc.Dataset.Tabular.from_pandas(df, dtype=dtype)

In [10]:
label = dataset.make_label(columns=['kingdom_category'])

In [11]:
featureset = dataset.make_featureset(exclude_columns=['kingdom_category'])

In [13]:
splitset = featureset.make_splitset(
    label_id=label.id
    , size_test = 0.22
    , size_validation = 0.12 
)

---

In [5]:
splitset = aiqc.Splitset.get_by_id(1)

In [6]:
encoderset = splitset.make_encoderset()

In [7]:
labelcoder = encoderset.make_labelcoder(
    sklearn_preprocess = OneHotEncoder()
    , only_fit_train = False
)

---

In [16]:
samples = splitset.to_pandas(splits=['train', 'validation', 'test'])

In [17]:
samples.keys()

dict_keys(['train', 'validation', 'test'])

In [18]:
samples['train']['labels']

kingdom_category
26            kokiri
24            kokiri
102           gerudo
69            hylian
30            kokiri
..               ...
10            kokiri
62            hylian
18            kokiri
114           gerudo
41            hylian

[78 rows x 1 columns]

---

In [37]:
class Preprocess:
    featureset_encoders:list
    label_encoder:object

In [38]:
preproc = Preprocess()

In [39]:
preproc.label_encoder = OneHotEncoder(sparse=False)

In [61]:
preproc.featureset_encoders = [
    {
       "all_columns": False #default True
        , "dtypes_include": ['float64', 'float32']
        , "dtypes_exclude": None
        , "columns_include": ['temperature_float']
        , "columns_exclude": None
        , "sklearn_preprocess": OrdinalEncoder()
    }
]

In [100]:
splitset.label.to_numpy()

array([['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['kokiri'],
       ['hylian'],
       ['hylian'],
       ['hylian'],
       ['hylian'],
       ['hylian'],
       ['hylian'],
       ['hylian'],
       ['hylian'],
       ['hylian'],
       ['hylian'],
       ['hylian'],
       ['hylian'],
       ['hyl

In [94]:
encoder = OrdinalEncoder()
encoder.fit_transform(splitset.to_numpy(splits=['train'])['train']['labels'])

array([[0.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [1.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],

- First, if the dtype filters exist, apply them.
  - If both None, then pass `df.select_dtypes(include=set(df.columns.to_list())))`
- Then get a list of remaining columns.
- Then include/exclude columns from that list.
- The remaining columns will be encoded by the encoded.

In [62]:
df

doom_float64  radiance_float32  temperature_float weekday_object  \
0       100000.50              -0.1                0.0         sunday   
1        99793.11              -0.2                1.5         monday   
2        99585.72              -0.3                3.0        tuesday   
3        99378.33              -0.4                4.5      wednesday   
4        99170.94              -0.5                6.0       thursday   
..            ...               ...                ...            ...   
115      76150.65             -11.6              172.5      wednesday   
116      75943.26             -11.7              174.0       thursday   
117      75735.87             -11.8              175.5         friday   
118      75528.48             -11.9              177.0       saturday   
119      75321.09             -12.0              178.5         sunday   

      hour_object  moonday_int64  month_int32  color_uint8  shape_int  \
0             one              1            1            0          0   
1             two              2            2            0          0   
2           three              3            3            0          0   
3            four              4            4            0          0   
4            five              5            5            0          0   
..            ...            ...          ...          ...        ...   
115        twenty             29            8            3          2   
116    twenty-one              1            9            3          2   
117    twenty-two              2           10            3          2   
118  twenty-three              3           11            3          2   
119   twenty-four              4           12            3          2   

    kingdom_category  
0             kokiri  
1             kokiri  
2             kokiri  
3             kokiri  
4             kokiri  
..               ...  
115           gerudo  
116           gerudo  
117           gerudo  
118           gerudo  
119           gerudo  

[120 rows x 10 columns]

In [63]:
e

[{'dtypes_include': ['float64', 'float32'],
  'dtypes_exclude': None,
  'columns_include': None,
  'columns_exclude': ['temperature_float'],
  'encoder': OrdinalEncoder()}]

In [76]:
all_filters_included_cols = []

In [83]:
if (
    (preproc.featureset_encoders[0]['dtypes_include'] is None)
    and
    (preproc.featureset_encoders[0]['dtypes_exclude'] is None)
):
    # If no dtype filters, just take all columns and move to next step.
    subset_columns = df.columns.to_list()
else:    
    subset_columns = df.select_dtypes(
        include = preproc.featureset_encoders[0]['dtypes_include']
        , exclude = preproc.featureset_encoders[0]['dtypes_exclude']
    ).columns.to_list()

In [75]:
subset_columns

['doom_float64', 'radiance_float32', 'temperature_float']

creation validation:

`.from_splitset`

splitset must be supervised to add a EncoderLabel
check len of relations on run.

== for each encoder ==
- Check `len(preprocess.encoderfeaturesets)` if > 1 then `all_columns` cannot be True.
- if `all_remaining_columns==True`... you cannot have more than 1 encoder. 
- if `all_remaining_columns==True`... then `dtypes_include` and `dtypes_exclude` cannot be set.
- Error if `sklearn_preprocess` is None.
- Error if `all_remaining_columns==False` and the include/excludes are all None.

== dtype ==
- can't have same the dtype in both include and exclude.
- if both None: pass #be explicit about it.
- validate that dtypes used are present in remaining featureset df. # this would happen in try?


== colnames ==
if both None: pass #be explicit about it.
if (not None): 
- #check if list empty. if (not mylist): raise ValueError 
- can't have same col_name in include and exclude.
- check that column name is present in remaining featureset df. # this would happen in try?


== try ===
- don't run if len 0
- run the entire chain of Preprocessset in order.
- try: except: else: it runs clean.

that way, when it comes time to run it, it can just be ran... because we know it will work. much better for UX too.

In [84]:
# start with this and keep pruning it.
# can continually check dtypes and cols of it.

#remaining_df = df
#remaining_cols = cols?

In [73]:
if (not subset_columns):
    raise ValueError("\nYikes - After applying `dtypes_include` and `dtypes exclude`, there are no columns left to work with.\n")

In [72]:
if (preproc.featureset_encoders[0]['columns_include'] is not None):
    # Move to creation.
    #if (preproc.featureset_encoders[0]['columns_exclude'] is not None):
    #    raise ValueError("\nYikes - Either `include_columns` or `exclude_columns` can be set, but not both.\n")    
    include = preproc.featureset_encoders[0]['columns_include']
    # Move to creation.
    #if (not include):
    #    raise ValueError("\nYikes - Inclusion/ exclusion lists can be None, but cannot be empty e.g. `[]`.\n")
    
    # `in` must be an exact match when used at the list level.
    # Partial matched like `"saw" in "sawdust"` don't trigger it.
    subset_columns = [c for c in subset_columns if c in include]

elif (preproc.featureset_encoders[0]['columns_exclude'] is not None):
    # Move to creation.
    #if (preproc.featureset_encoders[0]['columns_include'] is not None):
    #    raise ValueError("\nYikes - Either `include_columns` or `exclude_columns` can be set, but not both.\n")
    exclude = preproc.featureset_encoders[0]['columns_exclude']
    # Move to creation.
    #if (not exclude):
    #    raise ValueError("\nYikes - Inclusion/ exclusion lists can be None, but cannot be empty e.g. `[]`.\n") 
    subset_columns = [c for c in subset_columns if c not in exclude]

In [73]:
if (not subset_columns):
    raise ValueError("\nYikes - After applying `columns_include` and `columns_exclude`, there are no columns left to work with.\n")

check columns against macro list. 
error if they are found.
otherwise add them to the list.

df...selected_columns...straight to numpy

add to list of numpys

then prune original df.

run next filter.

after all filters, combine the numpys.

---

---

In [104]:
subset_details = preproc.featureset_encoder[0]

In [105]:
subset_encoder = subset_details['encoder']

In [106]:
subset = df.select_dtypes(subset_details['include'])

In [107]:
subset_cols = subset.columns.to_list()

In [108]:
subset_encoded_arr = subset_encoder.fit_transform(subset)

In [109]:
subset_details_2 = preproc.featureset_encoder[1]

In [110]:
subset_encoder_2 = subset_details_2['encoder']

In [111]:
subset_2 = df.select_dtypes(subset_details_2['include'])

In [112]:
subset_cols_2 = subset_2.columns.to_list()

In [113]:
subset_encoded_arr_2 = subset_encoder_2.fit_transform(subset_2)

In [114]:
subset_encoded_arr_2

array([[ 0.12052239, -0.73266327],
       [-1.28055041, -0.6812386 ],
       [ 1.16002802,  1.41390187]])

In [115]:
subset_encoded_arr

array([[0.],
       [1.],
       [2.]])

In [116]:
subset_encoded_arr_2

array([[ 0.12052239, -0.73266327],
       [-1.28055041, -0.6812386 ],
       [ 1.16002802,  1.41390187]])

In [117]:
np.concatenate((subset_encoded_arr, subset_encoded_arr_2), axis=-1)

array([[ 0.        ,  0.12052239, -0.73266327],
       [ 1.        , -1.28055041, -0.6812386 ],
       [ 2.        ,  1.16002802,  1.41390187]])

In [118]:
encoded_cols = []

In [119]:
for c in subset_cols:
    encoded_cols.append(c)

In [120]:
for c in subset_cols_2:
    encoded_cols.append(c)

In [121]:
encoded_cols

['mode', 'size', 'height']

In [125]:
# should do this as often as possible to reduce memory?
df = df[df.columns.difference(encoded_cols, sort=False)]

In [126]:
#df = df.drop(encoded_cols, axis=1)

In [127]:
df

name
0    bob
1    jim
2  larry

---

In [121]:
oher = OneHotEncoder()

In [122]:
oher.fit(df[['name']])

OneHotEncoder()

In [124]:
arr = oher.transform(df[['name']])

In [125]:
arr

<50x5 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [127]:
np.concatenate((subset_encoded_arr, subset_encoded_arr_2), axis=-1)

<1x5 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [130]:
str(type(arr))

"<class 'scipy.sparse.csr.csr_matrix'>"

In [131]:
arr.toarray()[:3]

array([[0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [279]:
ordiner = OrdinalEncoder()

In [280]:
ordiner.fit(df[['price']])

OrdinalEncoder()

In [281]:
arr = ordiner.transform(df[['price']])

In [282]:
arr[:10]

array([[31.],
       [27.],
       [39.],
       [38.],
       [41.],
       [36.],
       [29.],
       [35.],
       [12.],
       [17.]])