In [107]:
import numpy as np

In [108]:
from sklearn.preprocessing import *

In [109]:
array2D_2 = np.arange(10,16).reshape(3,2)

In [110]:
array2D_2

array([[10, 11],
       [12, 13],
       [14, 15]])

In [111]:
StandardScaler().fit_transform(array2D_2)

array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

In [112]:
array2D_2

array([[10, 11],
       [12, 13],
       [14, 15]])