In [1]:
import numpy as np

In [2]:
arr = [
    [1.1, 2.2, 3.3],
    [1.1, 2.2, 3.3],
    [1.1, 2.2, 3.3],
]

In [3]:
arr = np.array(arr)

In [4]:
arr

array([[1.1, 2.2, 3.3],
       [1.1, 2.2, 3.3],
       [1.1, 2.2, 3.3]])

In [5]:
arr / 1

array([[1.1, 2.2, 3.3],
       [1.1, 2.2, 3.3],
       [1.1, 2.2, 3.3]])

In [6]:
arr / 0.5

array([[2.2, 4.4, 6.6],
       [2.2, 4.4, 6.6],
       [2.2, 4.4, 6.6]])

In [ ]:
arr / 